#!/bin/bash

# This script generates the genesis file for Lighthouse

# Set the path to the Lighthouse binary
LIGHTHOUSE_BIN="./lighthouse"

# Set the path to the genesis configuration file
GENESIS_CONFIG="../genesis/genesis.json"

# Set the output path for the genesis.ssz file
OUTPUT_PATH="../genesis/genesis.ssz"

# Generate the genesis file using Lighthouse
$LIGHTHOUSE_BIN genesis init --config $GENESIS_CONFIG --output $OUTPUT_PATH

echo "Genesis file generated at $OUTPUT_PATH"