beacon_chain:
  data_dir: "./data"
  http_port: 4000
  grpc_port: 5000
  metrics_port: 8000
  min_peers: 5
  max_peers: 50
  bootstrap_nodes:
    - "enr:-J4Q...your_bootstrap_node_enr_here"
  
validator:
  data_dir: "./validator_data"
  http_port: 4001
  grpc_port: 5001
  metrics_port: 8001
  min_peers: 5
  max_peers: 50
  enable_validator_api: true
  validator_keys:
    - "./keys/validator_keys.json"

logging:
  level: "info"
  file: "./logs/prysm.log"

network:
  name: "your_network_name"
  chain_id: 1
  eth1_rpc: "http://localhost:8545"
  eth1_chain_id: 1

genesis:
  state: "./genesis.ssz"
  deposit_contract_address: "0xYourDepositContractAddressHere"