beacon_chain:
  chain_id: 12345
  min_peers: 2
  max_peers: 50
  data_dir: "./data"
  http:
    enabled: true
    port: 3500
  grpc:
    enabled: true
    port: 50051
  metrics:
    enabled: true
    port: 8080
  eth1:
    endpoint: "http://localhost:8545"
  deposit_contract_address: "0xYourDepositContractAddress"
  log_level: "info"
  persistence:
    db_backend: "leveldb"
    db_path: "./data/db"
  bootstrap_nodes:
    - "enr:-JQ4Q...YourBootstrapNodeENR"
    - "enr:-JQ4Q...AnotherBootstrapNodeENR"