network:
  name: "Ethereum PoS Private Chain"
  chain_id: 12345
  genesis_time: "2023-12-15T00:00:00Z"
  deposit_contract_address: "0xYourDepositContractAddress"
  initial_validators:
    - address: "0xYourValidatorAddress1"
      balance: "32000000000000000000"  # 32 ETH
    - address: "0xYourValidatorAddress2"
      balance: "32000000000000000000"  # 32 ETH
  bootnodes:
    - "enode://your_bootnode_enode@your_bootnode_ip:port"
  eth1:
    endpoint: "http://localhost:8545"
  beacon_chain:
    endpoint: "http://localhost:4000"
  validator:
    endpoint: "http://localhost:4001"